FROM  hashicorp/terraform:light 


RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN mkdir /terraform; chown -R appuser:appgroup /terraform
WORKDIR /terraform
USER appuser

ENTRYPOINT ["/bin/terraform"]

